## The dataset

-  1547 real patient cases on low back pain
- Outcome variable: Treatment 1-5

#### Research question
1. To what extend can one, based on the answers given in the questionnaire, automatically determine the
advised treatment for a patient with back pain.
2. To what extend can one reduce the number of questions, i.e. which questions can be left out without
major decrease in performance? <br>
Evaluate techniques beyond Decision Trees and Regression.

<h2 style="size:20px;">Input Variables</h2>
<table style="width: 100%;
            border-collapse: collapse;">
    <tr>
        <th>Variable</th>
        <th>Description</th>
    </tr>
    <tr>
        <td>Fever</td>
        <td>1=yes, 0=no</td>
    </tr>
    <tr>
        <td>Duration_in_years</td>
        <td>
            1 = 0-1 weeks <br>
            2 = 1-2 weeks <br>
            3 = 3-4 weeks <br>
            4 = 4-5 weeks <br>
            5 = 6-8 weeks <br>
            6 = 9-11 weeks <br>
            7 = 3-6 months <br>
            8 = 6-9 months <br>
            9 = 9-12 months <br>
            10 = more than 1 year
        </td>
    </tr>
    <tr>
        <td>Sick_leave</td>
        <td>1=yes, 0=no</td>
    </tr>
    <tr>
        <td>Earlier_hospitalization</td>
        <td>1=yes, 0=no</td>
    </tr>
    <tr>
        <td>Workoverload</td>
        <td>1=yes, 0=no</td>
    </tr>
    <tr>
        <td>Familiy_history</td>
        <td>1=yes, 0=no</td>
    </tr>
    <tr>
        <td>Depression</td>
        <td>1=yes, 0=no</td>
    </tr>
    <tr>
        <td>Extremely_nervous</td>
        <td>Value between 0 (not at all) and 10 (Very tense or anxious)</td>
    </tr>
    <tr>
        <td>Stress</td>
        <td>1=yes, 0=no</td>
    </tr>
    <tr>
        <td>Relationship_with_colleagues</td>
        <td>Value between 0 (not satisfied at all) and 10 (completely satisfied)</td>
    </tr>
    <tr>
        <td>Irrational_thoughts_risk_lasting</td>
        <td>Value between 0 (no risk) and 10 (Very high risk)</td>
    </tr>
    <tr>
        <td>Irrational_thoughts_work</td>
        <td>Value between 0 (fully disagree) and 10 (fully agree)</td>
    </tr>
    <tr>
        <td>Coping_strategy</td>
        <td>Value between 0 (not at all) and 10 (Can reduce the pain completely)</td>
    </tr>
    <tr>
        <td>Kinesiophobia_physical_exercise</td>
        <td>Value between 0 (fully disagree) and 10 (fully agree)</td>
    </tr>
    <tr>
        <td>Kinesiophobia_pain_stop</td>
        <td>Value between 0 (fully disagree) and 10 (fully agree)</td>
    </tr>
    <tr>
        <td>Age</td>
        <td>0-19, 20-29, â€¦.., >=80</td>
    </tr>
    <tr>
        <td>Uses_analgesics</td>
        <td>1=yes, 0=no</td>
    </tr>
    <tr>
        <td>Uses_corticosteroids</td>
        <td>1=yes, 0=no</td>
    </tr>
    <tr>
        <td>Serious_disease</td>
        <td>1=yes, 0=no</td>
    </tr>
    <tr>
        <td>Neurogenic_signals</td>
        <td>1=yes, 0=no</td>
    </tr>
    <tr>
        <td>Continuous_pain</td>
        <td>1=yes, 0=no</td>
    </tr>
    <tr>
        <td>Decreased_mobility</td>
        <td>Value</td>
    </tr>
    <tr>
        <td>Nocturnal_pain</td>
        <td>1=yes, 0=no</td>
    </tr>
    <tr>
        <td>Weightloss_per_year</td>
        <td>1=decrease, 2=increase, 3=stable, 4=fluctuating</td>
    </tr>
    <tr>
        <td>Loss_muscle_strength</td>
        <td>1=yes, 0=no</td>
    </tr>
    <tr>
        <td>Trauma</td>
        <td>1=yes, 0=no</td>
    </tr>
    <tr>
        <td>Failure_symptoms</td>
        <td>1=yes, 0=no</td>
    </tr>
    <tr>
        <td>Incoordination</td>
        <td>1=yes, 0=no</td>
    </tr>
    <tr>
        <td>Neck_pain_intensity</td>
        <td>Value between 0 (None) and 10 (Unbearable)</td>
    </tr>
    <tr>
        <td>Low_back_pain_intensity</td>
        <td>Value between 0 (None) and 10 (Unbearable)</td>
    </tr>
    <tr>
        <td>Arm_left_pain_intensity</td>
        <td>Value between 0 (None) and 10 (Unbearable)</td>
    </tr>
    <tr>
        <td>Arm_right_pain_intensity</td>
        <td>Value between 0 (None) and 10 (Unbearable)</td>
    </tr>
    <tr>
        <td>Leg_left_pain_intensity</td>
        <td>Value between 0 (None) and 10 (Unbearable)</td>
    </tr>
    <tr>
        <td>Leg_right_pain_intensity</td>
        <td>Value between 0 (None) and 10 (Unbearable)</td>
    </tr>
    <tr>
        <td>Working_ability</td>
        <td>Value between 0 and 10</td>
    </tr>
    <tr>
        <td>Paid_work</td>
        <td>1=yes, 0=no</td>
    </tr>
</table>

<h2>Outcome Variable</h2>
<table>
    <tr>
        <th>Variable</th>
        <th>Description</th>
    </tr>
    <tr>
        <td>Treatment</td>
        <td>
            1. Advice <br>
            2. Rehabilitation <br>
            3. Surgery <br>
            4. Injection/medication <br>
            5. Combination of 1-4
        </td>
    </tr>
</table>

To use the database, connect to bronto.ewi.utwente.nl using these credentials:

- Example command for connecting:
psql -h bronto.ewi.utwente.nl -U dab_ds2425-2a_10 dab_ds2425-2a_10

- https://bronto.ewi.utwente.nl/phppgadmin/

In [ ]:
import pandas as pd
from connection import *

print("Columns in dataset")
data = pd.read_excel("./data/Dataset - LBP RA.xlsx", sheet_name='Training Dataset')
print(data.columns)
##print(training_dataset.head())

# Create the Patient ID column
data.insert(0, 'Patient_ID', data.index)

data.head(10)

Columns in dataset
Index(['Treatment', 'Fever', 'Duration_of_pain', 'Sick_leave',
       'Earlier_hospitalization', 'Workoverload', 'Familiy_history',
       'Depression', 'Extremely_nervous', 'Stress',
       'Relationship_with_colleagues', 'Irrational_thoughts_risk_lasting',
       'Irrational_thoughts_work', 'Coping_strategy',
       'Kinesiophobia_physical_exercise', 'Kinesiophobia_pain_stop', 'Age',
       'Uses_analgesics', 'Uses_corticosteroids', 'Serious_disease',
       'Neurogenic_signals', 'Continuous_pain', 'Decreased_mobility',
       'Nocturnal_pain', 'Weightloss_per_year', 'Loss_muscle_strength',
       'Trauma', 'Failure_symptoms', 'Incoordination', 'neck_pain_intensity',
       'low_back_pain_intensity', 'arm_left_pain_intensity',
       'arm_right_pain_intensity', 'leg_left_pain_intensity',
       'leg_right_pain_intensity', 'working_ability', 'Paidwork'],
      dtype='object')

,Patient_ID,Treatment,Fever,Duration_of_pain,Sick_leave,Earlier_hospitalization,Workoverload,Familiy_history,Depression,Extremely_nervous,...,Failure_symptoms,Incoordination,neck_pain_intensity,low_back_pain_intensity,arm_left_pain_intensity,arm_right_pain_intensity,leg_left_pain_intensity,leg_right_pain_intensity,working_ability,Paidwork
0,0,1,1.0,10.0,0,1,NaN,0,0,0.0,...,1,NaN,0,8,8,7,6,6,NaN,0
1,1,3,1.0,10.0,0,1,0.0,1,0,0.0,...,1,1.0,7,8,7,4,0,0,7.0,1
2,2,1,1.0,10.0,0,1,NaN,0,0,6.0,...,1,0.0,3,5,0,2,0,3,NaN,0
3,3,5,1.0,10.0,0,1,NaN,0,0,1.0,...,0,NaN,2,9,0,0,9,5,NaN,0
4,4,1,1.0,10.0,0,1,NaN,0,0,0.0,...,1,NaN,0,7,5,0,0,0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1541,1541,5,0.0,8.0,1,0,NaN,0,0,3.0,...,1,0.0,0,8,0,0,0,0,NaN,1
1542,1542,1,0.0,10.0,0,0,1.0,0,0,0.0,...,1,NaN,0,10,0,0,0,9,NaN,0
1543,1543,1,0.0,10.0,0,1,NaN,1,1,8.0,...,1,1.0,0,8,0,0,0,8,NaN,0
1544,1544,1,0.0,10.0,1,1,NaN,1,0,3.0,...,1,1.0,0,8,0,0,0,0,1.0,1
1545,1545,1,0.0,9.0,0,0,NaN,0,0,5.0,...,1,0.0,0,8,0,0,8,8,5.0,1

# Data Preprocessing

### Missing Values

In [65]:
def checkNaNs(DF):
    print("Total rows in DF: ", len(DF))
    print("Total NaNs in DF: ",pd.isna(DF).sum().sum())
    #print(pd.isna(DF).sum())
    all_nans = pd.DataFrame(pd.isna(DF).sum())
    return all_nans
checkNaNs(data)

Total rows in DF:  1546
Total NaNs in DF:  4310

                                     0
Patient_ID                           0
Treatment                            0
Fever                               34
Duration_of_pain                    31
Sick_leave                           0
Earlier_hospitalization              0
Workoverload                      1087
Familiy_history                      0
Depression                           0
Extremely_nervous                   52
Stress                               0
Relationship_with_colleagues       567
Irrational_thoughts_risk_lasting    71
Irrational_thoughts_work           183
Coping_strategy                     70
Kinesiophobia_physical_exercise     51
Kinesiophobia_pain_stop             68
Age                                  0
Uses_analgesics                      0
Uses_corticosteroids                13
Serious_disease                     12
Neurogenic_signals                   0
Continuous_pain                      0
Decreased_mobility                   0
Nocturnal_pain                       0
Weightloss_per_year                 37
Loss_muscle_strength                82
Trauma                             680
Failure_symptoms                     0
Incoordination                     230
neck_pain_intensity                  0
low_back_pain_intensity              0
arm_left_pain_intensity              0
arm_right_pain_intensity             0
leg_left_pain_intensity              0
leg_right_pain_intensity             0
working_ability                   1042
Paidwork                             0

In [66]:
def remove_columns_nan(DF):
        """  
        Remove the columns where missing value are greater than 10% of total data
        """
        
        print("Columns in current dataset: ", len(DF.columns))    
        columns_to_remove = []
        for col,value in enumerate(pd.isna(DF).sum()):
            if (value/len(data))*100 > 10:
                #print(DF.columns[col])
                columns_to_remove.append(DF.columns[col])
        print("Columns with more than 10% of missing values: ",columns_to_remove)                       
        
        DF= DF.drop(columns=columns_to_remove)
        print("Columns in dataset after removal: ", len(DF.columns))       
        return DF
        
data_wo_cols = remove_columns_nan(data)

Columns in current dataset:  38
Columns with more than 10% of missing values:  ['Workoverload', 'Relationship_with_colleagues', 'Irrational_thoughts_work', 'Trauma', 'Incoordination', 'working_ability']
Columns in dataset after removal:  32

In [67]:
def groupbypatients_checkna(DF):
    """
    Remove patients with more than 20% of features missing values (5/6 columns)
    """
    print("Size of dataset before removal:", len(DF))

    #print("Features/",print(6/(37-4) *100)
    # Count NaNs per row (patient-wise)
    DF['Num_NaNs'] = DF.isna().sum(axis=1)

    # Determine threshold dynamically (20% of total columns)
    threshold = int(0.2 * (DF.shape[1] - 1))  # Exclude 'Patient_ID' column from count
    index_patients_nans = DF.loc[DF['Num_NaNs'] >= threshold, 'Patient_ID']

    print(f"Num of patients with NaN >= {threshold}: {len(index_patients_nans)}")

    # Remove patients that exceed the threshold
    DF = DF[~DF['Patient_ID'].isin(index_patients_nans)].drop(columns=['Num_NaNs'])

    print("Size of dataset after removal:", len(DF))
    
    return DF

data_wo_patients = groupbypatients_checkna(data_wo_cols)

Size of dataset before removal: 1546
Num of patients with NaN >= 6: 19
Size of dataset after removal: 1527

In [70]:
checkNaNs(data_wo_patients)

Total rows in DF:  1527
Total NaNs in DF:  404

                                   0
Patient_ID                         0
Treatment                          0
Fever                             33
Duration_of_pain                  13
Sick_leave                         0
Earlier_hospitalization            0
Familiy_history                    0
Depression                         0
Extremely_nervous                 33
Stress                             0
Irrational_thoughts_risk_lasting  52
Coping_strategy                   51
Kinesiophobia_physical_exercise   32
Kinesiophobia_pain_stop           49
Age                                0
Uses_analgesics                    0
Uses_corticosteroids              13
Serious_disease                   11
Neurogenic_signals                 0
Continuous_pain                    0
Decreased_mobility                 0
Nocturnal_pain                     0
Weightloss_per_year               36
Loss_muscle_strength              81
Failure_symptoms                   0
neck_pain_intensity                0
low_back_pain_intensity            0
arm_left_pain_intensity            0
arm_right_pain_intensity           0
leg_left_pain_intensity            0
leg_right_pain_intensity           0
Paidwork                           0

# First Data Visualization to understand how to impute the values

In [69]:
data.describe(include="all")

,Patient_ID,Treatment,Fever,Duration_of_pain,Sick_leave,Earlier_hospitalization,Workoverload,Familiy_history,Depression,Extremely_nervous,...,Failure_symptoms,Incoordination,neck_pain_intensity,low_back_pain_intensity,arm_left_pain_intensity,arm_right_pain_intensity,leg_left_pain_intensity,leg_right_pain_intensity,working_ability,Paidwork
count,1546.000000,1546.000000,1512.00000,1515.000000,1546.000000,1546.000000,459.000000,1546.000000,1546.000000,1494.000000,...,1546.000000,1316.000000,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000,504.000000,1546.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,772.500000,2.891979,0.27381,9.193399,0.301423,0.692109,0.400871,0.256792,0.093790,3.113119,...,0.892626,0.386018,1.596378,6.523933,0.706339,0.716041,2.805304,2.785899,4.696429,0.328590
std,446.436072,1.867272,0.44606,1.521821,0.459024,0.461771,0.490610,0.437005,0.291631,3.058689,...,0.309688,0.487020,2.764563,2.532330,1.967483,1.996168,3.454409,3.468595,2.632778,0.469853
min,0.000000,1.000000,0.00000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,386.250000,1.000000,0.00000,9.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000
50%,772.500000,2.000000,0.00000,10.000000,0.000000,1.000000,0.000000,0.000000,0.000000,2.000000,...,1.000000,0.000000,0.000000,7.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000
75%,1158.750000,5.000000,1.00000,10.000000,1.000000,1.000000,1.000000,1.000000,0.000000,6.000000,...,1.000000,1.000000,3.000000,8.000000,0.000000,0.000000,6.000000,6.000000,7.000000,1.000000
max,1545.000000,5.000000,1.00000,10.000000,1.000000,1.000000,1.000000,1.000000,1.000000,10.000000,...,1.000000,1.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000

In [73]:
data['Trauma'].value_counts(dropna=False)

Trauma
NaN    680
0.0    617
1.0    249
Name: count, dtype: int64

In [ ]:
import numpy as np 
from sqlalchemy import create_engine 

import psycopg2

DB_HOST = DB_HOST
DB_NAME = DB_NAME
DB_USER = DB_USER       
DB_PASS = DB_PASS       
DB_PORT = DB_PORT               # Default PostgreSQL port

# SQL queries to create tables
CREATE_TABLES_SQL = """
    CREATE TABLE IF NOT EXISTS project.customer (
        customerid SERIAL PRIMARY KEY,
        name VARCHAR(100),
        country VARCHAR(100)
    );

    CREATE TABLE IF NOT EXISTS project.product (
        productid SERIAL PRIMARY KEY,
        name VARCHAR(100),
        category VARCHAR(100)
    );

    CREATE TABLE IF NOT EXISTS project.sales (
        orderdate DATE NOT NULL,
        customerid INTEGER NOT NULL,
        productid INTEGER NOT NULL,
        sales DOUBLE PRECISION,
        PRIMARY KEY (orderdate, customerid, productid)
    );
"""

try:
    # Connect to PostgreSQL
    conn = psycopg2.connect(
        dbname=DB_NAME, user=DB_USER, password=DB_PASS, host=DB_HOST, port=DB_PORT
    )
    conn.autocommit = True  # Ensure changes are saved automatically

    # Create a cursor object
    cursor = conn.cursor()

    # Execute table creation queries
    cursor.execute(CREATE_TABLES_SQL)

    print("Tables created successfully.")

    # Close the cursor and connection
    cursor.close()
    conn.close()

except Exception as e:
    print("Error:", e)
    
#engine = create_engine(f'postgresql://{DB_NAME}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}')
# product.to_sql('product', engine, schema='ass2', index=False, if_exists='replace')

NameError: name 'DB_HOST' is not defined

In [6]:
from sqlalchemy import create_engine 

engine = create_engine(f'postgresql://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}')

product = pd.read_sql('SELECT * FROM ass2.product', engine)
customers = pd.read_sql('SELECT * FROM ass2.customer', engine)
sales = pd.read_sql('SELECT * FROM ass2.sales', engine)

print(product.head())
print(customers.head())
print(sales.head())

   productid              name      category
0          0   Mishi Kobe Niku  Meat/Poultry
1          1    Sirop d'Ã©rable    Condiments
2          2         Chocolade   Confections
3          3       RÃ¸gede sild       Seafood
4          4  Valkoinen suklaa   Confections
   customerid                  name  country
0           0  La corne d'abondance   France
1           1  SpÃ©cialitÃ©s du monde   France
2           2   France restauration   France
3           3   Alfreds Futterkiste  Germany
4           4       The Cracker Box      USA
    orderdate  customerid  productid  sales
0  2009-10-09          37         56  244.3
1  2009-10-09          82         55  190.0
2  2009-10-09          82         38   36.0
3  2009-10-09          82         23  360.0
4  2009-10-09          40         14  500.0